server:
  port: 8080
spring:
  main:
    banner-mode: "off"
  h2:
    console.enabled: true
    console.settings.trace: false
    console:
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop
#      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2