server:
  port: 8080
spring:
  main:
    banner-mode: "off"
  h2:
    console.enabled: true
    console.settings.trace: false
  datasource:
    url: jdbc:h2:file:./data/horticula
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect